# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25780ced766558e19d77a4d5aa58ce6c89374884c20c38ccddac4e336ff3160da0c12eeafb2af7bf6e250561c4f2545e4b909e6f7e074a8cda113f5a94a535e3

test:
  secret_key_base: 165a8844fd29c1a7c7bfe2e75812b0fd90f656adb5248fbec3baca689b1018d36c52a194eb41b18e17d64f5922a33ac94bc0c1d7f1ebf50d76e16d55c5fd1697

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
